# Common configuration.
AllCops:
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - vendor/assets/bower_components/**/*
    - Rakefile
    - Guardfile
    - bin/*
    - db/**/*
    - config/**/*
    - script/**/*
    - Rakefile
    - tmp/**/*
    - vendor/**/*
    - spec/support/**/*
    - ./*.gemspec
    - lib/hosts-ruby.rb
    - test/**/*

LineLength:
  Enabled: true
  Max: 80

Documentation:
  Enabled: false

AlignHash:
  Enabled: false

# Buggy cop:
EndOfLine:
  Enabled: false

AsciiComments:
  Enabled: false

# Not working for breaks_paid? method
TrivialAccessors:
  Enabled: false

# Disabled since renaming has methods makes no sense
PredicateName:
  Enabled: false

IndentationConsistency:
  Enabled: false

ConditionPosition:
  Enabled: false

# We want to use the compact style of module definitions
ClassAndModuleChildren:
  Enabled: false

# Buggy cop:
BlockAlignment:
  Enabled: false

MethodLength:
  Enabled: false

AbcSize:
  Enabled: false
